-- ansi.lua — a colorscheme built entirely from the terminal's 16 ANSI colors.
-- Ported from Ham Vocke's "An ANSI color scheme for Vim":
-- https://hamvocke.com/blog/ansi-vim-color-scheme/
--
-- It relies on cterm colors so it inherits whatever palette your terminal
-- emulator is themed with. That only works with termguicolors OFF, which this
-- file enforces below.

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then
  vim.cmd('syntax reset')
end

vim.o.background = 'dark'
vim.o.termguicolors = false
vim.g.colors_name = 'ansi'

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local function link(group, target)
  vim.api.nvim_set_hl(0, group, { link = target })
end

-- Editor elements
hi('NonText', { ctermfg = 0 })
hi('Ignore', {})
hi('Underlined', { cterm = { underline = true } })
hi('Bold', { cterm = { bold = true } })
hi('Italic', { cterm = { italic = true } })
hi('StatusLine', { ctermfg = 15, ctermbg = 8 })
hi('StatusLineNC', { ctermfg = 15, ctermbg = 0 })
hi('VertSplit', { ctermfg = 8 })
hi('TabLine', { ctermfg = 7, ctermbg = 0 })
hi('TabLineFill', { ctermfg = 0 })
hi('TabLineSel', { ctermfg = 0, ctermbg = 11 })
hi('Title', { ctermfg = 4, cterm = { bold = true } })
hi('CursorLine', { ctermbg = 0 })
hi('Cursor', { ctermfg = 0, ctermbg = 15 })
hi('CursorColumn', { ctermbg = 0 })
hi('LineNr', { ctermfg = 8 })
hi('CursorLineNr', { ctermfg = 6 })
hi('helpLeadBlank', {})
hi('helpNormal', {})
hi('Visual', { ctermfg = 15, ctermbg = 8, cterm = { bold = true } })
hi('VisualNOS', { ctermfg = 15, ctermbg = 8, cterm = { bold = true } })
hi('Pmenu', { ctermfg = 15, ctermbg = 0 })
hi('PmenuSbar', { ctermfg = 7, ctermbg = 8 })
hi('PmenuSel', { ctermfg = 15, ctermbg = 8, cterm = { bold = true } })
hi('PmenuThumb', { ctermbg = 7 })
hi('FoldColumn', { ctermfg = 7 })
hi('Folded', { ctermfg = 12 })
hi('WildMenu', { ctermfg = 15, ctermbg = 0 })
hi('SpecialKey', { ctermfg = 0 })
hi('IncSearch', { ctermfg = 0, ctermbg = 1 })
hi('CurSearch', { ctermfg = 0, ctermbg = 3 })
hi('Search', { ctermfg = 0, ctermbg = 11 })
hi('Directory', { ctermfg = 4 })
hi('MatchParen', { ctermfg = 3, ctermbg = 0, cterm = { underline = true } })
hi('SpellBad', { cterm = { undercurl = true } })
hi('SpellCap', { cterm = { undercurl = true } })
hi('SpellLocal', { cterm = { undercurl = true } })
hi('SpellRare', { cterm = { undercurl = true } })
hi('ColorColumn', { ctermbg = 8 })
hi('SignColumn', { ctermfg = 7 })
hi('ModeMsg', { ctermfg = 0, ctermbg = 15, cterm = { bold = true } })
hi('MoreMsg', { ctermfg = 4 })
hi('Question', { ctermfg = 4 })
hi('QuickFixLine', { ctermfg = 14, ctermbg = 0 })
hi('Conceal', { ctermfg = 8 })
hi('ToolbarLine', { ctermfg = 15, ctermbg = 0 })
hi('ToolbarButton', { ctermfg = 15, ctermbg = 8 })
hi('debugPC', { ctermfg = 7 })
hi('debugBreakpoint', { ctermfg = 8 })
hi('ErrorMsg', { ctermfg = 1, cterm = { bold = true, italic = true } })
hi('WarningMsg', { ctermfg = 11 })
hi('DiffAdd', { ctermfg = 0, ctermbg = 10 })
hi('DiffChange', { ctermfg = 0, ctermbg = 12 })
hi('DiffDelete', { ctermfg = 0, ctermbg = 9 })
hi('DiffText', { ctermfg = 0, ctermbg = 14 })
hi('diffAdded', { ctermfg = 10 })
hi('diffRemoved', { ctermfg = 9 })
hi('diffChanged', { ctermfg = 12 })
hi('diffOldFile', { ctermfg = 11 })
hi('diffNewFile', { ctermfg = 13 })
hi('diffFile', { ctermfg = 12 })
hi('diffLine', { ctermfg = 7 })
hi('diffIndexLine', { ctermfg = 14 })
hi('healthError', { ctermfg = 1 })
hi('healthSuccess', { ctermfg = 2 })
hi('healthWarning', { ctermfg = 3 })

-- Syntax
hi('Comment', { ctermfg = 8, cterm = { italic = true } })
hi('Constant', { ctermfg = 3 })
hi('Error', { ctermfg = 1 })
hi('Identifier', { ctermfg = 9 })
hi('Function', { ctermfg = 4 })
hi('Special', { ctermfg = 13 })
hi('Statement', { ctermfg = 5 })
hi('String', { ctermfg = 2 })
hi('Operator', { ctermfg = 6 })
hi('Boolean', { ctermfg = 3 })
hi('Label', { ctermfg = 14 })
hi('Keyword', { ctermfg = 5 })
hi('Exception', { ctermfg = 5 })
hi('Conditional', { ctermfg = 5 })
hi('PreProc', { ctermfg = 13 })
hi('Include', { ctermfg = 5 })
hi('Macro', { ctermfg = 5 })
hi('StorageClass', { ctermfg = 11 })
hi('Structure', { ctermfg = 11 })
hi('Todo', { ctermfg = 0, ctermbg = 9, cterm = { bold = true } })
hi('Type', { ctermfg = 11 })

-- Neovim floating windows
hi('NormalFloat', { ctermfg = 15, ctermbg = 0 })
hi('FloatBorder', { ctermfg = 7, ctermbg = 0 })
hi('FloatShadow', { ctermfg = 15, ctermbg = 0 })

-- Treesitter
hi('@variable', { ctermfg = 15 })
hi('@variable.builtin', { ctermfg = 1 })
hi('@variable.parameter', { ctermfg = 1 })
hi('@variable.member', { ctermfg = 1 })
hi('@constant.builtin', { ctermfg = 5 })
hi('@string.regexp', { ctermfg = 1 })
hi('@string.escape', { ctermfg = 6 })
hi('@string.special.url', { ctermfg = 4, cterm = { underline = true } })
hi('@string.special.symbol', { ctermfg = 13 })
hi('@type.builtin', { ctermfg = 3 })
hi('@property', { ctermfg = 1 })
hi('@function.builtin', { ctermfg = 5 })
hi('@constructor', { ctermfg = 11 })
hi('@keyword.coroutine', { ctermfg = 1 })
hi('@keyword.function', { ctermfg = 5 })
hi('@keyword.return', { ctermfg = 5 })
hi('@keyword.export', { ctermfg = 14 })
hi('@punctuation.bracket', { ctermfg = 15 })
hi('@comment.error', { ctermfg = 0, ctermbg = 9 })
hi('@comment.warning', { ctermfg = 0, ctermbg = 11 })
hi('@comment.todo', { ctermfg = 0, ctermbg = 12 })
hi('@comment.note', { ctermfg = 0, ctermbg = 14 })
hi('@markup', { ctermfg = 15 })
hi('@markup.strong', { ctermfg = 15, cterm = { bold = true } })
hi('@markup.italic', { ctermfg = 15, cterm = { italic = true } })
hi('@markup.strikethrough', { ctermfg = 15, cterm = { strikethrough = true } })
hi('@markup.heading', { ctermfg = 4, cterm = { bold = true } })
hi('@markup.quote', { ctermfg = 6 })
hi('@markup.math', { ctermfg = 4 })
hi('@markup.link.url', { ctermfg = 5, cterm = { underline = true } })
hi('@markup.raw', { ctermfg = 14 })
hi('@markup.list.checked', { ctermfg = 2 })
hi('@markup.list.unchecked', { ctermfg = 7 })
hi('@tag', { ctermfg = 5 })
hi('@tag.builtin', { ctermfg = 6 })
hi('@tag.attribute', { ctermfg = 4 })
hi('@tag.delimiter', { ctermfg = 15 })

-- Treesitter links to standard groups
link('@variable.parameter.builtin', '@variable.parameter')
link('@constant', 'Constant')
link('@constant.macro', 'Macro')
link('@module', 'Structure')
link('@module.builtin', 'Special')
link('@label', 'Label')
link('@string', 'String')
link('@string.special', 'Special')
link('@character', 'Character')
link('@character.special', 'SpecialChar')
link('@boolean', 'Boolean')
link('@number', 'Number')
link('@number.float', 'Float')
link('@type', 'Type')
link('@type.definition', 'Type')
link('@attribute', 'Constant')
link('@attribute.builtin', 'Constant')
link('@function', 'Function')
link('@function.call', 'Function')
link('@function.method', 'Function')
link('@function.method.call', 'Function')
link('@operator', 'Operator')
link('@keyword', 'Keyword')
link('@keyword.operator', 'Operator')
link('@keyword.import', 'Include')
link('@keyword.type', 'Keyword')
link('@keyword.modifier', 'Keyword')
link('@keyword.repeat', 'Repeat')
link('@keyword.debug', 'Exception')
link('@keyword.exception', 'Exception')
link('@keyword.conditional', 'Conditional')
link('@keyword.conditional.ternary', 'Operator')
link('@keyword.directive', 'PreProc')
link('@keyword.directive.define', 'Define')
link('@punctuation.delimiter', 'Delimiter')
link('@punctuation.special', 'Special')
link('@comment', 'Comment')
link('@comment.documentation', 'Comment')
link('@markup.underline', 'Underlined')
link('@markup.link', 'Tag')
link('@markup.link.label', 'Label')
link('@markup.list', 'Special')
link('@diff.plus', 'diffAdded')
link('@diff.minus', 'diffRemoved')
link('@diff.delta', 'diffChanged')
